# -*- coding: utf-8 -*-
"""Project-- Scraping of Multiple pages website

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_6-5E6hxOi3vd_etSESVaz6B_NTHAMj
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

books = []
for i in range(1,51):
  url = f"https://books.toscrape.com/catalogue/page-{i}.html"
  page = requests.get(url)
  #response = page.content
  #soup = BeautifulSoup(response, "html.parser")
  soup = BeautifulSoup(page.text, "html")
  table = soup.find("ol")
  articles = table.find_all("article", class_="product_pod")
  for article in articles:
      image = article.find("img")
      title = image.attrs['alt']
      star = article.find('p')
      star = star['class'][1]
      price = article.find('p', class_ = 'price_color').text[2:]
      price = float(price)
      books.append([title,price,star])

df = pd.DataFrame(books, columns = ['Title', 'Price', 'Star Rating'])
df

df.to_csv('books.csv')





